# Generated by Django 5.1.3 on 2024-11-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
