# Generated by Django 5.1.3 on 2024-11-24 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_alter_participant_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='event',
            field=models.ForeignKey(choices=[('new_year', 'New Year'), ('christmas', 'Christmas'), ('christmas_eve', 'Christmas Eve')], on_delete=django.db.models.deletion.CASCADE, to='Events.event'),
        ),
    ]
